### ISSUE TITLE
Add validation for non-text responses

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqJSClient#15]

**Comment by robbertkl** [comment]
Just to get you started, here's 1 possible way to do it:

* let Axios pass the response as a buffer:
```ts
  responseType: "arraybuffer",
```
* in the data to verify, after the 2 newlines, append the binary string version of the buffer:
```ts
data = response.data.toString("binary");
...
const template: string = `${response.status}\n${headers}\n\n${data}`;
```
* let your `verifyString` function use raw encoding instead of utf-8:
```ts
messageDigest.update(data, "raw");
```

This preserves the binary encoding in the whole chain.

The same will also work just fine for regular JSON responses, but make sure you manually convert the response data to JSON, as Axios won't do this anymore because of the `responseType` option; something like:
```ts
if (response.headers["content-type"] === "application/json") {
  response.data = JSON.parse(response.data.toString("utf8"));
}
```

Technically, I don't think this last `"utf8"` is strictly necessary (i.e. could be `"latin1"` just as well), because the encoded JSON will contain escaped UTF-8 characters in embedded strings, should the response contain UTF-8 (e.g. an emoji in your bank account name).
